# Generated by Django 3.2 on 2021-06-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_name', models.CharField(max_length=200)),
                ('price_open', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date open')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='trade_close',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_close', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date open')),
                ('open_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.users'),
        ),
    ]
